# Generated by Django 2.2.19 on 2021-04-10 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'permissions': (('see_private_problem', 'See hidden problems'), ('edit_own_problem', 'Edit own problems'), ('edit_all_problem', 'Edit all problems'), ('edit_public_problem', 'Edit all public problems'), ('clone_problem', 'Clone problem'), ('change_public_visibility', 'Change is_public field'), ('change_manually_managed', 'Change is_manually_managed field')), 'verbose_name': 'problem', 'verbose_name_plural': 'problems'},
        ),
        migrations.RemoveField(
            model_name='contest',
            name='is_rated',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='rate_all',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='rate_exclude',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='rating_ceiling',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='rating_floor',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='use_clarifications',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='view_contest_scoreboard',
        ),
    ]
